### ISSUE TITLE
Build PR 968 Crashes on Full Screen

### ISSUE THREAD

**Issue by EricParker20** [vircadia/vircadia#994] opened 2021-01-31 21:35 UTC
Any adjustment to the size of the screen causes the app to crash on my machine. Using a 2019 MacBook Pro 16" with Catalina
<img width="582" alt="Screen Shot 2021-01-27 at 11 12 42 PM" src="https://user-images.githubusercontent.com/78323566/106398678-48cbb300-63e2-11eb-8aad-03921a6e2253.png">

**Comment by digisomni** [comment] 2021-02-01 21:49
This is likely because the PR builds are not being built with the proper SDK, so this is a known issue.

**Comment by Steve-Pruneau** [comment] 2021-02-03 21:36
I am surprised this has come up. It was intended to have been resolved back around August - September 2020 by @YuriKiev. And I believe it was solved for a version or 2 since August - September 2020 which I had tested. But I confirm, it is happening again even on my iMac.

**Comment by digisomni** [comment] 2021-02-03 21:38
This is not happening on a full release though right? This is simply because we did not alter the build process in GitHub Actions to do it I'd think.

I do not believe anyone has this issue in 2020.3.3.

**Comment by Steve-Pruneau** [comment] 2021-02-03 22:04
> This is not happening on a full release though right? This is simply because we did not alter the build process in GitHub Actions to do it I'd think.
> 
> I do not believe anyone has this issue in 2020.3.3.

CORRECT. Apologies for the confusion.

**Comment by daleglass** [comment] 2021-07-17 19:01
If this is related to the linked issue, it should be fixed. Please retest.

**Comment by JulianGro** [comment] 2021-10-12 14:52
PR builds still crash as the issue was never fixed.

**Closed** 2021-12-01 23:48 UTC
Labels: bug, Severity: Medium, confirmed, macos
